### ISSUE TITLE
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = org.achartengine.chart.LineChart)

### ISSUE THREAD

**Issue by xylik** [ddanny/achartengine#490]
Hi, not all demo examples(charts that are being sent through intent to GraphicalActivity) are working on my Android(4.4 KitKat) phone because XYChart.java and TimeChart.java contains android.graphics.Paint class(mGridPaint variable) which cannot be serialized when sending through Intent. 

I hacked examples by setting problematic Paint object as transient and providing it directly to GraphicalActivity through static field and re-setting it on graph object pulled from intent. 

The problem should be solved adequately because less experience Android developers could just give up on such good library... And here is the stackTrace just in case:

01-12 05:32:22.396 29503-29503/? E/AndroidRuntime: FATAL EXCEPTION: main
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime: Process: org.achartengine.chartdemo.demo, PID: 29503
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime: java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = org.achartengine.chart.LineChart)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.os.Parcel.writeSerializable(Parcel.java:1316)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.os.Parcel.writeValue(Parcel.java:1264)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.os.Parcel.writeArrayMapInternal(Parcel.java:618)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.os.Bundle.writeToParcel(Bundle.java:1692)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.os.Parcel.writeBundle(Parcel.java:636)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.content.Intent.writeToParcel(Intent.java:7244)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2153)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1425)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.app.Activity.startActivityForResult(Activity.java:3457)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.app.Activity.startActivityForResult(Activity.java:3418)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.app.Activity.startActivity(Activity.java:3660)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.app.Activity.startActivity(Activity.java:3628)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at org.achartengine.chartdemo.demo.ChartDemo.onListItemClick(ChartDemo.java:111)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.app.ListActivity$2.onItemClick(ListActivity.java:319)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.widget.AdapterView.performItemClick(AdapterView.java:299)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.widget.AbsListView.performItemClick(AbsListView.java:1152)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.widget.AbsListView$PerformClick.run(AbsListView.java:3014)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.widget.AbsListView$3.run(AbsListView.java:3865)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:808)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:103)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:193)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5292)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:  Caused by: java.io.NotSerializableException: android.graphics.Paint
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1342)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1649)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1495)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1459)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:957)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1052)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1382)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1649)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1495)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1459)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.os.Parcel.writeSerializable(Parcel.java:1311)
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.os.Parcel.writeValue(Parcel.java:1264) 
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.os.Parcel.writeArrayMapInternal(Parcel.java:618) 
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.os.Bundle.writeToParcel(Bundle.java:1692) 
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.os.Parcel.writeBundle(Parcel.java:636) 
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.content.Intent.writeToParcel(Intent.java:7244) 
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2153) 
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1425) 
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.app.Activity.startActivityForResult(Activity.java:3457) 
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.app.Activity.startActivityForResult(Activity.java:3418) 
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.app.Activity.startActivity(Activity.java:3660) 
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.app.Activity.startActivity(Activity.java:3628) 
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at org.achartengine.chartdemo.demo.ChartDemo.onListItemClick(ChartDemo.java:111) 
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.app.ListActivity$2.onItemClick(ListActivity.java:319) 
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.widget.AdapterView.performItemClick(AdapterView.java:299) 
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.widget.AbsListView.performItemClick(AbsListView.java:1152) 
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.widget.AbsListView$PerformClick.run(AbsListView.java:3014) 
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.widget.AbsListView$3.run(AbsListView.java:3865) 
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:808) 
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:103) 
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:193) 
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5292) 
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515) 
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828) 
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644) 
01-12 05:32:22.396 29503-29503/? E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

**Comment by myria24** [comment]
1. Add SPaint.java
package org.achartengine.chart;
import android.graphics.Paint;
import java.io.Serializable;

public class SPaint extends Paint implements Serializable {
    public SPaint(int flags) {
        super(flags);
    }
}

2. Replace Paint with SPaint

**Comment by jxdnsong** [comment]
Hey, how did you solve the problem? I tried this method.But it's no use.Can you please share?

**Comment by ddanny** [comment]
Please pull from git, it is fixed now.
